"""Build the RAG corpus from the PubMed Central Open Access subset.

The chatbot answers a clinician's questions by grounding on real ophthalmology
literature rather than on the language model's parametric memory. That literature
has to be legally reusable and machine-readable, which is exactly what the
**PMC Open Access subset** provides: full-text articles, many under Creative
Commons licences, served as structured JATS XML through NCBI's E-utilities.

The pipeline here is three steps, all over free HTTP endpoints:

1. ``search_pmc`` - ``esearch`` finds article ids for a query, restricted to the
   open-access subset so everything we download is redistributable.
2. ``fetch_jats`` - ``efetch`` returns the full text of one article as JATS XML.
3. ``parse_jats`` - pull the title, DOI, journal, licence and the body broken
   into ``(section_title, text)`` pairs. Section structure is kept because it is
   what a section-aware chunker (see :mod:`ocular.rag.chunk`) later exploits, and
   the DOI/licence travel with every chunk so answers can cite their source.

The corpus scope is a **whitelist of ophthalmology journals**: an article that
appears in one of them is on-topic by virtue of its venue, so relevance filtering
needs no content model - the whitelist *is* the relevance filter. ``build_corpus``
searches that whitelist and ``save_corpus`` persists the result; the runnable
driver lives in ``scripts/build_corpus.py``, keeping this module a pure library in
the same spirit as the rest of ``ocular``.

Notes
-----
NCBI asks callers to identify themselves and to stay under a request-rate cap
(three requests per second anonymously, ten with a free API key). Both are
handled by :func:`_eutils_get`, which reads ``NCBI_API_KEY`` and ``NCBI_EMAIL``
from the environment and sleeps between calls accordingly.
"""
from __future__ import annotations

import json
import os
import re
import time
import urllib.parse
import urllib.request
from collections import Counter
from copy import deepcopy
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd
from lxml import etree
from tqdm import tqdm

from ocular import config

# Root of the corpus tree. Derived from the single source of truth in config so
# the whole data layout stays rooted at one place; it is git-ignored like the
# rest of data/ and regenerated by scripts/build_corpus.py.
CORPUS_DIR = config.DATA_DIR / "corpus"

# NCBI E-utilities. esearch resolves a query to article ids; efetch returns the
# full text of one article as JATS XML.
_EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"

# The corpus scope: a whitelist of ophthalmology journals. Every article in one
# of these is on-topic by venue, which makes the whitelist the relevance filter -
# no content classifier needed. Names are PubMed journal-field values (NLM
# abbreviations); extend the list to widen coverage.
OPHTHALMOLOGY_JOURNALS = [
    "Ophthalmology",
    "JAMA Ophthalmol",
    "Am J Ophthalmol",
    "Br J Ophthalmol",
    "Retina",
    "Ophthalmol Retina",
    "Ophthalmol Sci",
    "Invest Ophthalmol Vis Sci",
    "Transl Vis Sci Technol",
    "Prog Retin Eye Res",
    "Eye (Lond)",
    "Acta Ophthalmol",
    "Graefes Arch Clin Exp Ophthalmol",
    "BMC Ophthalmol",
    "Clin Ophthalmol",
]


def _journal_term(journals: list[str]) -> str:
    """Build the PMC search term restricting results to a set of journals."""
    return "(" + " OR ".join(f'"{j}"[Journal]' for j in journals) + ")"

# NCBI's polite-use rate cap: 10 requests/second with an API key, 3 without.
_DELAY = 0.11 if os.getenv("NCBI_API_KEY") else 0.34


@dataclass
class Document:
    """One parsed open-access article.

    Attributes
    ----------
    pmcid : str
        PubMed Central id, including the ``PMC`` prefix.
    title : str
        Article title.
    doi : str or None
        Digital Object Identifier, when the record carries one.
    license : str
        Licence label pulled from the article's ``<permissions>`` block (e.g.
        ``CC BY``), used both for citation and to screen out licences the project
        does not want to redistribute.
    journal : str
        Journal title.
    sections : list of tuple of (str, str)
        The article body as ``(section_title, text)`` pairs, abstract first, in
        reading order. Nested sections are flattened with their heading path
        joined by `` > `` so a chunker can still see where each block sits.
    """

    pmcid: str
    title: str
    doi: str | None
    license: str
    journal: str
    sections: list[tuple[str, str]] = field(default_factory=list)

    @property
    def full_text(self) -> str:
        """The whole article as one string, each section under its heading."""
        return "\n\n".join(f"{title}\n{text}" for title, text in self.sections)


def _eutils_get(endpoint: str, params: dict[str, str]) -> bytes:
    """Call an E-utilities endpoint, honouring NCBI's identification and rate rules.

    Parameters
    ----------
    endpoint : str
        Endpoint name, e.g. ``"esearch.fcgi"`` or ``"efetch.fcgi"``.
    params : dict of str to str
        Query parameters specific to the endpoint. ``tool``, ``email`` and
        ``api_key`` are added automatically from the environment.

    Returns
    -------
    bytes
        The raw response body.
    """
    params = {
        "tool": "ocular-scan-ai",
        "email": os.getenv("NCBI_EMAIL", ""),
        **params,
    }
    if key := os.getenv("NCBI_API_KEY"):
        params["api_key"] = key
    url = f"{_EUTILS}/{endpoint}?{urllib.parse.urlencode(params)}"
    time.sleep(_DELAY)
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read()


def search_pmc(query: str, retmax: int = 15) -> list[str]:
    """Find open-access PMC article ids for a query.

    Parameters
    ----------
    query : str
        A PMC search term, e.g. the journal-whitelist expression from
        :func:`_journal_term`. The open-access filter is appended here so callers
        need not repeat it.
    retmax : int, optional
        Maximum number of ids to return. Defaults to 15.

    Returns
    -------
    list of str
        PubMed Central ids, newest first, each with the ``PMC`` prefix.
    """
    body = _eutils_get(
        "esearch.fcgi",
        {
            "db": "pmc",
            "term": f'{query} AND "open access"[filter]',
            "retmax": str(retmax),
            "retmode": "json",
            # Most-recent-first: a journal-only scope has no query terms to rank
            # by relevance, and recency is the sensible order for a clinical
            # corpus, so `retmax` keeps the newest articles.
            "sort": "pub_date",
        },
    )
    idlist = json.loads(body)["esearchresult"].get("idlist", [])
    return [f"PMC{pmcid}" for pmcid in idlist]


def fetch_jats(pmcid: str) -> bytes:
    """Fetch the full text of one article as JATS XML.

    Parameters
    ----------
    pmcid : str
        PubMed Central id, with or without the ``PMC`` prefix.

    Returns
    -------
    bytes
        The JATS XML document.
    """
    numeric = pmcid.removeprefix("PMC")
    return _eutils_get(
        "efetch.fcgi", {"db": "pmc", "id": numeric, "retmode": "xml"}
    )


def _node_text(el: etree._Element | None) -> str:
    """Flatten an element's text, dropping cross-references and floats.

    ``<xref>`` (citation and figure markers such as ``[12]``), ``<fig>`` and
    ``<table-wrap>`` are stripped before the text is read, so a paragraph reads
    as prose rather than as prose peppered with reference numbers. Whitespace is
    collapsed to single spaces.
    """
    if el is None:
        return ""
    node = deepcopy(el)
    etree.strip_elements(node, "xref", "fig", "table-wrap", with_tail=False)
    text = re.sub(r"\s+", " ", "".join(node.itertext())).strip()
    return re.sub(r"\s+([.,;:)])", r"\1", text)  # tidy space left by stripped xrefs


def _license(article: etree._Element) -> str:
    """Reduce an article's ``<permissions>`` block to a short licence label.

    JATS records state the licence inconsistently: sometimes as a ``license-type``
    attribute, sometimes only as a Creative Commons URL (in an ``xlink:href``, an
    ``<ali:license_ref>`` or the licence prose). A Creative Commons URL is the
    most reliable signal, so it is matched first and normalised to a label such
    as ``CC BY 4.0``; otherwise the ``license-type`` attribute or a short prefix
    of the prose is used, and ``unknown`` when nothing is present.
    """
    el = article.find(".//article-meta/permissions/license")
    if el is None:
        return "unknown"
    href = el.get("{http://www.w3.org/1999/xlink}href") or ""
    ref = el.find(".//{*}license_ref")
    blob = " ".join([href, ref.text if ref is not None and ref.text else "", _node_text(el)])
    if m := re.search(r"creativecommons\.org/licenses/([a-z-]+)/(\d(?:\.\d)?)", blob):
        return f"CC {m.group(1).upper()} {m.group(2)}"
    return el.get("license-type") or (_node_text(el)[:40] or "unknown")


def _sections(el: etree._Element, prefix: str = "") -> list[tuple[str, str]]:
    """Recursively flatten ``<sec>`` blocks into ``(heading_path, text)`` pairs.

    Parameters
    ----------
    el : lxml.etree._Element
        The ``<body>`` element, or a ``<sec>`` during recursion.
    prefix : str, optional
        Heading path accumulated from enclosing sections, joined by `` > ``.

    Returns
    -------
    list of tuple of (str, str)
        One pair per section that carries paragraph text, in reading order.
    """
    out: list[tuple[str, str]] = []
    for sec in el.findall("sec"):
        title = _node_text(sec.find("title"))
        heading = f"{prefix}{title}" if title else prefix.rstrip(" > ")
        text = "\n".join(t for p in sec.findall("p") if (t := _node_text(p)))
        if text:
            out.append((heading or "Body", text))
        out.extend(_sections(sec, prefix=f"{heading} > " if heading else prefix))
    return out


def parse_jats(xml: bytes, pmcid: str) -> Document | None:
    """Parse one JATS XML document into a :class:`Document`.

    Parameters
    ----------
    xml : bytes
        The JATS XML returned by :func:`fetch_jats`.
    pmcid : str
        The article's PubMed Central id, used as the returned document's id.

    Returns
    -------
    Document or None
        The parsed article, or ``None`` when the record has no usable body (for
        example a correction notice or a record served without full text).
    """
    root = etree.fromstring(xml, etree.XMLParser(recover=True))
    article = root.find(".//article")
    if article is None:
        return None

    title = _node_text(article.find(".//article-meta/title-group/article-title"))
    journal = _node_text(article.find(".//journal-meta//journal-title"))
    doi_el = article.find(".//article-meta/article-id[@pub-id-type='doi']")
    doi = doi_el.text.strip() if doi_el is not None and doi_el.text else None

    license = _license(article)

    sections: list[tuple[str, str]] = []
    if abstract := _node_text(article.find(".//article-meta/abstract")):
        sections.append(("Abstract", abstract))
    if (body := article.find(".//body")) is not None:
        sections.extend(_sections(body))

    if not sections:
        return None
    return Document(pmcid, title, doi, license, journal, sections)


def is_permitted(license: str, allow_noncommercial: bool = False) -> bool:
    """Whether a licence permits the reuse a RAG corpus needs.

    Chunking an article and feeding the pieces to a model produces a derivative
    work and redistributes the text, so any **NoDerivatives** (``ND``) licence is
    excluded outright, as is anything that is not a recognised Creative Commons
    or public-domain licence - an unknown or publisher-specific licence cannot be
    assumed to grant those rights. **NonCommercial** (``NC``) licences are
    excluded by default and admitted only when ``allow_noncommercial`` is set,
    for a project that will stay non-commercial.

    Parameters
    ----------
    license : str
        A normalised licence label from :func:`_license`, e.g. ``"CC BY 4.0"``.
    allow_noncommercial : bool, optional
        Admit ``CC BY-NC`` / ``CC BY-NC-SA`` licences. Defaults to False.

    Returns
    -------
    bool
        True when the licence clearly permits the corpus's reuse.
    """
    lic = license.upper()
    if lic.startswith("CC0") or lic == "PUBLIC-DOMAIN":
        return True
    if not lic.startswith("CC "):
        return False
    if "ND" in lic:
        return False
    if "NC" in lic and not allow_noncommercial:
        return False
    return True


def build_corpus(
    journals: list[str] | None = None,
    limit: int | None = None,
    allow_noncommercial: bool = False,
) -> list[Document]:
    """Search a journal whitelist, then fetch, parse and licence-filter the articles.

    The scope is the set of ``journals`` (defaulting to :data:`OPHTHALMOLOGY_JOURNALS`),
    restricted to the open-access subset. Ids come back ranked, so ``limit`` keeps
    the top-N. Network or parse failures on a single article are warned about and
    skipped rather than aborting the build, and articles whose licence does not
    permit reuse (see :func:`is_permitted`) are dropped with a per-licence tally.

    Parameters
    ----------
    journals : list of str, optional
        Journal whitelist defining the corpus scope. Defaults to
        :data:`OPHTHALMOLOGY_JOURNALS`.
    limit : int, optional
        Maximum articles to fetch, top-ranked first. ``None`` fetches the whole
        scope, up to the 9,999-id ceiling of a single esearch call.
    allow_noncommercial : bool, optional
        Keep ``CC BY-NC`` articles as well. Defaults to False.

    Returns
    -------
    list of Document
        The parsed articles whose licence permits reuse.
    """
    journals = journals or OPHTHALMOLOGY_JOURNALS
    pmcids = search_pmc(_journal_term(journals), retmax=limit or 9999)

    docs: list[Document] = []
    dropped: Counter[str] = Counter()
    for pmcid in tqdm(pmcids, desc="fetching PMC"):
        try:
            doc = parse_jats(fetch_jats(pmcid), pmcid)
        except Exception as exc:  # network hiccup or malformed record: skip it
            print(f"  skip {pmcid}: {exc}")
            continue
        if doc is None:
            continue
        if not is_permitted(doc.license, allow_noncommercial):
            dropped[doc.license] += 1
            continue
        docs.append(doc)

    if dropped:
        print(f"  dropped {sum(dropped.values())} on licence: {dict(dropped)}")
    return docs


def save_corpus(docs: list[Document], out_dir: Path | None = None) -> None:
    """Write the corpus to ``corpus.jsonl`` and a ``metadata.csv`` index.

    ``corpus.jsonl`` holds one document per line (id, bibliographic fields and
    sections) for the indexer to read; ``metadata.csv`` is a human-readable
    manifest - one row per article with its licence and size - for eyeballing
    what was collected and checking licences at a glance.

    Parameters
    ----------
    docs : list of Document
        The documents to persist.
    out_dir : pathlib.Path, optional
        Destination directory. Defaults to :data:`CORPUS_DIR`.
    """
    out_dir = out_dir or CORPUS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    with (out_dir / "corpus.jsonl").open("w", encoding="utf-8") as fh:
        for doc in docs:
            fh.write(
                json.dumps(
                    {
                        "pmcid": doc.pmcid,
                        "title": doc.title,
                        "doi": doc.doi,
                        "license": doc.license,
                        "journal": doc.journal,
                        "sections": [list(s) for s in doc.sections],
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )

    pd.DataFrame(
        [
            {
                "pmcid": doc.pmcid,
                "title": doc.title,
                "doi": doc.doi,
                "license": doc.license,
                "journal": doc.journal,
                "n_sections": len(doc.sections),
                "n_chars": len(doc.full_text),
            }
            for doc in docs
        ]
    ).to_csv(out_dir / "metadata.csv", index=False)


def load_corpus(corpus_dir: Path | None = None) -> list[Document]:
    """Read a saved corpus back into :class:`Document` objects.

    This is the inverse of :func:`save_corpus`, used by the chunking and indexing
    stages to read the persisted ``corpus.jsonl`` without touching the network.

    Parameters
    ----------
    corpus_dir : pathlib.Path, optional
        Directory holding ``corpus.jsonl``. Defaults to :data:`CORPUS_DIR`.

    Returns
    -------
    list of Document
        The documents in the order they were written.
    """
    corpus_dir = corpus_dir or CORPUS_DIR
    docs: list[Document] = []
    with (corpus_dir / "corpus.jsonl").open(encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            docs.append(
                Document(
                    r["pmcid"],
                    r["title"],
                    r["doi"],
                    r["license"],
                    r["journal"],
                    [tuple(section) for section in r["sections"]],
                )
            )
    return docs
